version: "3.8"

services:
  web:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres5:password5@db:5432/mnist_db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres5
      POSTGRES_PASSWORD: password5
      POSTGRES_DB: mnist_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
